[[redirects]]
  from = "/*"
  to = "https://foodies-schiller.cyclic.app/"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "index.html"
  status = 200
  
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"